"""Per-game forecast computation: confidence interval, tier label, premium fields.

Pure computation given (sport, predicted_p, reliability_table). Backs
the /api/v1/games/{game_id}/forecast endpoint.

Specifications (memory: confidence_disclosure_ux_options_2026-05-29.md):
  Spec 2 — visual treatment + tier brackets:
    CI half-width ≤ 5pp → "Confident pick"
    6-10pp              → "Lean"
    11-15pp             → "Toss-up"
    > 15pp              → "Long shot"

  Spec 5 — premium-detail block fields

Reliability table is the per-sport per-decile (n, mean_predicted,
mean_observed, gap) blob generated by
`scripts/generate_reliability_table.py` from the Phase 6 K-fold
isotonic run output.

Special-case: when a sport's predicted-decile bin n < TAIL_MIN_N=139
AND that sport's overall calibration slope is in band, fall back to
the adjacent better-populated decile's gap. Avoids wild CI swings
from underpowered tail bins (Football D1 n=32; Boys Basketball D10
n=54). The fallback is conservative — uses the larger gap between
the decile and its neighbor.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


# Tier bracket constants — Spec 2 verbatim
TIER_CONFIDENT_PICK_MAX_HW: int = 5    # ≤ 5pp → Confident pick
TIER_LEAN_MAX_HW: int = 10             # 6-10pp → Lean
TIER_TOSS_UP_MAX_HW: int = 15          # 11-15pp → Toss-up
                                       # > 15pp → Long shot

# Statistical-power floor for the tail-bin fallback (matches
# engine.validator.runner_v2.PHASE6_TAIL_MIN_N = 139)
TAIL_MIN_N: int = 139


@dataclass(frozen=True)
class ForecastResult:
    """Output of forecast computation for one game."""
    home_win_probability: int               # 0..100, integer percent
    home_win_probability_ci_low: int        # 0..100, integer percent
    home_win_probability_ci_high: int       # 0..100, integer percent
    confidence_tier: str                    # enum code
    confidence_tier_label: str              # human-readable
    predicted_decile: int                   # 0..9, the decile p falls into
    underpowered_tail_fallback_used: bool   # diagnostic; True if used adjacent bin


def confidence_tier(ci_half_width_pp: int) -> tuple[str, str]:
    """Map CI half-width (integer percentage points) to tier code + label.

    Brackets per Spec 2:
      ≤ 5  → confident_pick / "Confident pick"
      6-10 → lean / "Lean"
      11-15 → toss_up / "Toss-up"
      > 15 → long_shot / "Long shot"
    """
    if ci_half_width_pp <= TIER_CONFIDENT_PICK_MAX_HW:
        return ("confident_pick", "Confident pick")
    if ci_half_width_pp <= TIER_LEAN_MAX_HW:
        return ("lean", "Lean")
    if ci_half_width_pp <= TIER_TOSS_UP_MAX_HW:
        return ("toss_up", "Toss-up")
    return ("long_shot", "Long shot")


def _predicted_decile(p: float) -> int:
    """Map a probability p in [0, 1] to a decile index 0..9.

    Right edge inclusive only on D9 so p=1.0 doesn't out-index.
    """
    if p < 0.0:
        return 0
    if p >= 1.0:
        return 9
    return min(9, int(p * 10))


def _lookup_decile_gap(
    sport_table: dict[str, Any],
    decile_idx: int,
) -> tuple[float, int]:
    """Return (gap, n_games) for sport's decile, or (0.0, 0) if missing."""
    deciles = sport_table.get("deciles", [])
    if not (0 <= decile_idx < len(deciles)):
        return 0.0, 0
    d = deciles[decile_idx]
    return float(d.get("gap", 0.0)), int(d.get("n_games", 0))


def _resolve_ci_half_width(
    sport_table: dict[str, Any],
    decile_idx: int,
) -> tuple[float, bool]:
    """Resolve the CI half-width (in probability units, NOT pp) for a decile.

    If the decile's n_games < TAIL_MIN_N and the sport's overall
    calibration slope is in band, fall back to the adjacent
    better-populated decile (whichever has more n). Returns
    (half_width_prob_units, fallback_used).

    The slope-in-band check is the safety net: if the sport itself
    is poorly calibrated, we should NOT swap in a healthier bin's
    gap because the whole sport is unreliable. Only use the fallback
    when overall calibration is good AND the local decile is sparse.
    """
    primary_gap, primary_n = _lookup_decile_gap(sport_table, decile_idx)

    if primary_n >= TAIL_MIN_N or not sport_table.get("isotonic_slope_in_band", False):
        return primary_gap, False

    # Try adjacent deciles
    candidates: list[tuple[float, int, int]] = [(primary_gap, primary_n, decile_idx)]
    for offset in (-1, +1):
        adj = decile_idx + offset
        if 0 <= adj < len(sport_table.get("deciles", [])):
            adj_gap, adj_n = _lookup_decile_gap(sport_table, adj)
            candidates.append((adj_gap, adj_n, adj))

    # Pick the candidate with the most n_games (best-populated)
    best = max(candidates, key=lambda c: c[1])
    if best[2] == decile_idx:
        # No better neighbor; stick with primary
        return primary_gap, False

    # Use the better-populated neighbor's gap
    return best[0], True


def compute_forecast(
    home_win_probability: float,
    sport_name: str,
    reliability_table: dict[str, Any],
) -> ForecastResult:
    """Compute the full forecast: probability, CI, tier label.

    Args:
        home_win_probability: probability in [0, 1] from the engine
        sport_name: canonical sport name (e.g., "Football")
        reliability_table: the loaded JSON dict from
            data/calibration/phase6_reliability_table.json

    Returns:
        ForecastResult with integer-pp fields and tier metadata.
    """
    p = max(0.0, min(1.0, float(home_win_probability)))
    p_pct = round(100 * p)
    decile_idx = _predicted_decile(p)

    sport_table = reliability_table.get("sports", {}).get(sport_name, {})
    half_width_prob, fallback_used = _resolve_ci_half_width(sport_table, decile_idx)
    half_width_pp = round(100 * half_width_prob)

    ci_low_pp = max(0, p_pct - half_width_pp)
    ci_high_pp = min(100, p_pct + half_width_pp)

    tier_code, tier_label = confidence_tier(half_width_pp)

    return ForecastResult(
        home_win_probability=int(p_pct),
        home_win_probability_ci_low=int(ci_low_pp),
        home_win_probability_ci_high=int(ci_high_pp),
        confidence_tier=tier_code,
        confidence_tier_label=tier_label,
        predicted_decile=decile_idx,
        underpowered_tail_fallback_used=fallback_used,
    )


def build_premium_detail(
    sport_name: str,
    home_team_id: int,
    away_team_id: int,
    predicted_decile: int,
    reliability_table: dict[str, Any],
    home_typical_decile: int | None = None,
    away_typical_decile: int | None = None,
) -> dict[str, Any]:
    """Build the premium_detail block for authenticated premium responses.

    Per Spec 5: coefficients + typical-decile per team + predicted-bucket
    reliability + methodology deep-link.

    The typical-decile fields are passed in (computed elsewhere from
    per-team aggregates); this function just packages everything.
    """
    sport_table = reliability_table.get("sports", {}).get(sport_name, {})
    coefs = sport_table.get("model_coefficients", {})

    decile_reliability: dict[str, Any] | None = None
    deciles = sport_table.get("deciles", [])
    if 0 <= predicted_decile < len(deciles):
        d = deciles[predicted_decile]
        decile_reliability = {
            "n_games": int(d.get("n_games", 0)),
            "gap": float(d.get("gap", 0.0)),
            "mean_predicted": d.get("mean_predicted"),
            "mean_observed": d.get("mean_observed"),
        }

    # Methodology deep-link: /methodology#<sport-slug>-d<decile+1>
    sport_slug = sport_name.lower().replace(" ", "-")
    methodology_link = f"/methodology#{sport_slug}-d{predicted_decile + 1}"

    return {
        "model_coefficients": dict(coefs),
        "home_typical_decile": home_typical_decile,
        "away_typical_decile": away_typical_decile,
        "predicted_decile": predicted_decile,
        "predicted_decile_reliability": decile_reliability,
        "methodology_deep_link": methodology_link,
    }
