"""Per-game forecast computation: confidence interval, tier label, premium fields.

Pure computation given (sport, predicted_p, reliability_table). Backs
the /api/v1/games/{game_id}/forecast endpoint.

CI METHODOLOGY (Option D, locked 2026-05-29 evening per decisions.md):

  Binomial sampling CI on the per-bin observed proportion:
      half_width = 1.96 × √(p_obs × (1 - p_obs) / n)

  where p_obs is the empirical home-win proportion in the decile
  bin the prediction falls into, and n is the bin's sample size from
  the locked Phase 6 K-fold isotonic holdout.

  This replaces the pre-Option-D CI = bin gap. The gap measures
  bin-level CALIBRATION (model-vs-reality residual); the binomial CI
  measures SAMPLING UNCERTAINTY on the observed proportion. The
  user-facing question "how confident should I be in this prediction?"
  maps to sampling uncertainty, not calibration residual.

  The bin gap (calibration metric) is still exposed via the premium
  drawer and the /methodology page as a complementary engineer-facing
  number. See decisions.md 2026-05-29 evening + arc-patterns pattern
  #8 extension.

Specifications (memory: confidence_disclosure_ux_options_2026-05-29.md):
  Spec 2 (revised 2026-05-29 evening):
    CI half-width ≤ 5pp → "Confident pick"  ← UI shipped at v1.0
    6-10pp              → "Lean"            ← UI shipped at v1.0
    11-15pp             → "Toss-up"         ← API enum only; not UI
    > 15pp              → "Long shot"       ← API enum only; not UI

  4-tier API enum preserved for extensibility; UI ships 2-tier.

  Spec 5 — premium-detail block fields

Reliability table is the per-sport per-decile (n, mean_predicted,
mean_observed, gap) blob generated by
`scripts/generate_reliability_table.py` from the Phase 6 K-fold
isotonic run output.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any


# Tier bracket constants — Spec 2 (4-tier enum; 2 surfaced in v1.0 UI)
TIER_CONFIDENT_PICK_MAX_HW: int = 5    # ≤ 5pp → Confident pick (UI)
TIER_LEAN_MAX_HW: int = 10             # 6-10pp → Lean (UI)
TIER_TOSS_UP_MAX_HW: int = 15          # 11-15pp → Toss-up (API only at v1.0)
                                       # > 15pp → Long shot (API only at v1.0)

# Z-value for 95% confidence interval on a binomial proportion
Z_95 = 1.96

# Statistical-power floor for tail-bin handling. Same constant as
# engine.validator.runner_v2.PHASE6_TAIL_MIN_N — retained for the
# premium drawer "is this bin underpowered?" flag, but no longer
# gates CI computation (Option D's binomial CI handles small-n bins
# correctly by widening the CI as n shrinks — exactly the behavior
# the prior fallback was simulating).
TAIL_MIN_N: int = 139


@dataclass(frozen=True)
class ForecastResult:
    """Output of forecast computation for one game."""
    home_win_probability: int               # 0..100, integer percent
    home_win_probability_ci_low: int        # 0..100, integer percent
    home_win_probability_ci_high: int       # 0..100, integer percent
    confidence_tier: str                    # enum code (4 values; 2 surfaced)
    confidence_tier_label: str              # human-readable
    predicted_decile: int                   # 0..9, the decile p falls into
    bin_n_games: int                        # n in the predicted decile bin
    bin_underpowered: bool                  # bin_n < TAIL_MIN_N (diagnostic)


def confidence_tier(ci_half_width_pp: int) -> tuple[str, str]:
    """Map CI half-width (integer percentage points) to tier code + label.

    Brackets per Spec 2:
      ≤ 5  → confident_pick / "Confident pick"
      6-10 → lean / "Lean"
      11-15 → toss_up / "Toss-up"
      > 15 → long_shot / "Long shot"
    """
    if ci_half_width_pp <= TIER_CONFIDENT_PICK_MAX_HW:
        return ("confident_pick", "Confident pick")
    if ci_half_width_pp <= TIER_LEAN_MAX_HW:
        return ("lean", "Lean")
    if ci_half_width_pp <= TIER_TOSS_UP_MAX_HW:
        return ("toss_up", "Toss-up")
    return ("long_shot", "Long shot")


def _predicted_decile(p: float) -> int:
    """Map a probability p in [0, 1] to a decile index 0..9.

    Right edge inclusive only on D9 so p=1.0 doesn't out-index.
    """
    if p < 0.0:
        return 0
    if p >= 1.0:
        return 9
    return min(9, int(p * 10))


def _lookup_decile_metrics(
    sport_table: dict[str, Any],
    decile_idx: int,
) -> tuple[float, float, int]:
    """Return (p_obs, gap, n_games) for sport's decile.

    p_obs = mean_observed home-win proportion in the bin (for the
            binomial CI computation).
    gap   = abs(mean_predicted - mean_observed); calibration metric
            kept for the premium drawer + methodology page.
    n     = sample size of the bin.

    Returns (0.0, 0.0, 0) if the decile is missing or empty.
    """
    deciles = sport_table.get("deciles", [])
    if not (0 <= decile_idx < len(deciles)):
        return 0.0, 0.0, 0
    d = deciles[decile_idx]
    p_obs_raw = d.get("mean_observed")
    if p_obs_raw is None:
        return 0.0, float(d.get("gap", 0.0)), int(d.get("n_games", 0))
    return float(p_obs_raw), float(d.get("gap", 0.0)), int(d.get("n_games", 0))


def _binomial_ci_half_width(p_obs: float, n: int) -> float:
    """95% binomial sampling CI half-width on an observed proportion.

    half_width = 1.96 × √(p(1-p)/n)

    Returns 0.0 for empty bins (n=0). Clipped at 0.5 (=50pp) as a
    safety ceiling — bins that small would never realistically
    surface a prediction anyway.
    """
    if n <= 0:
        return 0.0
    # Clip p_obs to (0, 1) to avoid zero-variance edge cases at the
    # exact endpoints when a bin has 0% or 100% observed proportion.
    p = max(0.001, min(0.999, p_obs))
    return min(0.5, Z_95 * math.sqrt(p * (1 - p) / n))


def compute_forecast(
    home_win_probability: float,
    sport_name: str,
    reliability_table: dict[str, Any],
) -> ForecastResult:
    """Compute the full forecast: probability, CI, tier label.

    Args:
        home_win_probability: probability in [0, 1] from the engine
        sport_name: canonical sport name (e.g., "Football")
        reliability_table: the loaded JSON dict from
            data/calibration/phase6_reliability_table.json

    Returns:
        ForecastResult with integer-pp fields and tier metadata.
    """
    p = max(0.0, min(1.0, float(home_win_probability)))
    p_pct = round(100 * p)
    decile_idx = _predicted_decile(p)

    sport_table = reliability_table.get("sports", {}).get(sport_name, {})
    p_obs, _bin_gap, bin_n = _lookup_decile_metrics(sport_table, decile_idx)
    half_width_prob = _binomial_ci_half_width(p_obs, bin_n)
    half_width_pp = round(100 * half_width_prob)

    ci_low_pp = max(0, p_pct - half_width_pp)
    ci_high_pp = min(100, p_pct + half_width_pp)

    tier_code, tier_label = confidence_tier(half_width_pp)

    return ForecastResult(
        home_win_probability=int(p_pct),
        home_win_probability_ci_low=int(ci_low_pp),
        home_win_probability_ci_high=int(ci_high_pp),
        confidence_tier=tier_code,
        confidence_tier_label=tier_label,
        predicted_decile=decile_idx,
        bin_n_games=bin_n,
        bin_underpowered=(bin_n < TAIL_MIN_N),
    )


def build_premium_detail(
    sport_name: str,
    home_team_id: int,
    away_team_id: int,
    predicted_decile: int,
    reliability_table: dict[str, Any],
    home_typical_decile: int | None = None,
    away_typical_decile: int | None = None,
) -> dict[str, Any]:
    """Build the premium_detail block for authenticated premium responses.

    Per Spec 5: coefficients + typical-decile per team + predicted-bucket
    reliability + methodology deep-link.

    The typical-decile fields are passed in (computed elsewhere from
    per-team aggregates); this function just packages everything.
    """
    sport_table = reliability_table.get("sports", {}).get(sport_name, {})
    coefs = sport_table.get("model_coefficients", {})

    decile_reliability: dict[str, Any] | None = None
    deciles = sport_table.get("deciles", [])
    if 0 <= predicted_decile < len(deciles):
        d = deciles[predicted_decile]
        decile_reliability = {
            "n_games": int(d.get("n_games", 0)),
            "gap": float(d.get("gap", 0.0)),
            "mean_predicted": d.get("mean_predicted"),
            "mean_observed": d.get("mean_observed"),
        }

    # Methodology deep-link: /methodology#<sport-slug>-d<decile+1>
    sport_slug = sport_name.lower().replace(" ", "-")
    methodology_link = f"/methodology#{sport_slug}-d{predicted_decile + 1}"

    return {
        "model_coefficients": dict(coefs),
        "home_typical_decile": home_typical_decile,
        "away_typical_decile": away_typical_decile,
        "predicted_decile": predicted_decile,
        "predicted_decile_reliability": decile_reliability,
        "methodology_deep_link": methodology_link,
    }
